FROM node:22-bookworm-slim

RUN echo "deb http://ftp.tw.debian.org/debian sid main contrib" >> /etc/apt/sources.list

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y python3 ttf-mscorefonts-installer dnsutils build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev \
    && apt-get clean

RUN corepack enable pnpm 

RUN pnpm config set auto-install-peers true

WORKDIR /app

COPY package.json /app
COPY pnpm-lock.yaml /app

RUN pnpm i

COPY . /app

RUN pnpm prisma generate
