FROM node:16-bullseye AS build

WORKDIR /app

COPY package* /app
RUN npm i

COPY . /app
RUN npm run build

FROM node:16-bullseye 

WORKDIR /app

RUN echo "deb http://ftp.tw.debian.org/debian sid main contrib" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y ttf-mscorefonts-installer dnsutils
RUN apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
COPY --from=build /app/dist/index.js .

